### ISSUE TITLE
When should release 1.3.0 come out - is this repo actively maintained?

### ISSUE THREAD

**Issue by rafaelbattesti** [segmentio/analytics-python#174]
I am working on integrating generic Python backends with Segment.
I have a requirement to set the message ids from the backend client and noticed the last release available is `1.2.9` while there is code in the master branch that would allow me to do that, fixed on `analytics-python==1.3.0b0`.

Is anyone maintaining this repo?
Do you need help maintaining the repo?

**Comment by steinnes** [comment]
I've been running the 1.3.x branch for over a year now, and I can report that it's quite stable.  That said I would be happy to contribute to development here in order to get the new version released.

Considering the level of sophistication generally encountered at Segment, I find this repository a bit scruffy.  Needs love, and the community can probably provide some :-)

**Comment by heitorsampaio** [comment]
https://github.com/segmentio/analytics-python/issues/152#issuecomment-805948936
