### ISSUE TITLE
Package name should NOT be "analytics", rename to segment/segmentio

### ISSUE THREAD

**Issue by alvinchow86** [segmentio/analytics-python#42]
The top-level package name really should be something unique, like **segmentio** or something. If you have another package or module loaded in your Python load path named analytics, a very common word, there is a name-space collision and it's possible (or very difficult) to resolve in Python

``` python
# import analytics
import segmentio
```

**Comment by tedmiston** [comment]
+1

It's kind of a pain to workaround this when we have a local app in our django project already called analytics.

**Comment by graingert** [comment]
:+1:

**Comment by saebyn** [comment]
:+1:

**Comment by zen-jyoo** [comment]
+1

**Comment by zartux** [comment]
:+1:

**Comment by adamchainz** [comment]
@alvinchow86 you can solve the import collision by turning off implicit relative imports in Python 2.7 with

```py
from __future__ import absolute_import
```

However this has been a big readability hassle for us as we had lots of code written generically for whatever analytics service(s) we'd use, and when we switched to Segment it became unreadable.

We now do:

```py
import analytics as segment
```

etc. everywhere we use it!

**Comment by tedmiston** [comment]
@alvinchow86 @adamchainz We can, but _shouldn't_ have to do that.

> I find that use of "import ... as" is often an anti-pattern or a code smell
>
> —Guido

http://code.activestate.com/lists/python-ideas/30361/

**Comment by tedmiston** [comment]
@alvinchow86 We can, but _shouldn't_ have to do that.

> I find that use of "import ... as" is often an anti-pattern or a code
smell
>
> —Guido

http://code.activestate.com/lists/python-ideas/30361/

**Comment by rhaarm** [comment]
Is it possible to consider changing this package name, or do I need to change it locally and rebase every time there is an update?

**Comment by graingert** [comment]
```bash
pip install segment
```

```python
import segment
```

**Comment by adamchainz** [comment]
@graingert you better keep that up to date

**Comment by tuxxy** [comment]
Is there a reason why this issue was closed? It's an exceptionally valid issue. My org is running into this issue right now and it appears many others are.

Let's not be unreasonable and come up with a valid solution, please. 👍

**Comment by graingert** [comment]
@tuxxy probably better to stick with `pip install segment` I'm happy to add contributors to the project

**Comment by astrodsg** [comment]
@graingert that seems like a good solution. Thought the `segment` version doesn't seem to have been updated in a long time (v0.2.0 instead of anaytics-python v1.2.5). Could it be updated with every new github release for the analytics-python repo?

**Comment by astrodsg** [comment]
@graingert why is the version v0.2.0 and not v1.2.5 if it's suppose to be just a wrapper?

**Comment by f2prateek** [comment]
@graingert's wrapper is following it's own versioning scheme (independent of analytics-python's versioning). If you download the source code from https://pypi.python.org/pypi/segment/0.2.0, you'll see it has the latest relevant changes (commit in our repo https://github.com/segmentio/analytics-python/pull/79, and in segment package on pypi https://cloudup.com/c4EegesqVjE).

Effectively it's up to to date with version 1.2.5

**Comment by graingert** [comment]
It's not a wrapper

**Comment by graingert** [comment]
I'll transfer the name across if segment want to keep it updated

**Comment by pusnik** [comment]
+1

**Comment by jhh3000** [comment]
+1

**Comment by jamiemccrindle** [comment]
+1

**Comment by jamiemccrindle** [comment]
I've created a renamed version at https://pypi.python.org/pypi/segmentio for anyone who needs it. Repo at https://github.com/jamiemccrindle/segmentio.

**Comment by jordanambra** [comment]
Thanks @jamiemccrindle. We have this same issue.

**Comment by f2prateek** [comment]
Tracking internally here as well https://segment.atlassian.net/browse/LIB-115

**Comment by f2prateek** [comment]
Renaming the package name to `segment` doesn't seem like a practical solution here. Here's a good discussion (albeit in Ruby) around this https://github.com/rails/journey/issues/49#issuecomment-8720991.

https://github.com/segmentio/analytics-python/issues/42#issuecomment-218803671

This seems like a reasonable workaround. Are there any practical concerns to not using this (other than Guido's comment from http://code.activestate.com/lists/python-ideas/30361)

**Comment by graingert** [comment]
Please just rename the module and bump the major version

**Comment by f2prateek** [comment]
@graingert I don't think's a practical solution here - someone could easily have a module named segment and we'll be back to square one. 

What are your arguments against https://github.com/segmentio/analytics-python/issues/42#issuecomment-218803671?

**Comment by graingert** [comment]
That's fine because it matches your PyPI name

**Comment by adamchainz** [comment]
@f2prateek 'as' imports *are* a bit ugly, and make the code harder to read. If you can just rename it once and solve it for everyone then that is the easiest path

**Comment by jordanambra** [comment]
I don't understand why you're worried that someone's going to have a module named segment but not worried that someone's going to have a module named analytics. Analytics is a common module name I've seen in 6 different companies so far; probably nobody else is calling their module segment except for you guys, and I'm sure they would be empathetic if they had a conflict since you have a brand around it.

**Comment by f2prateek** [comment]
I have the following concerns with renaming to `segment`:
* Making people have to update their code and migrate their implementations to accomadete this change
* It's also about consistency, we have 10 other using the same name `analytics` (https://github.com/segmentio?utf8=✓&q=analytics&type=&language=).
* the problem isn't fully 100% mitigated. I understand how fewer people will run into a conflict with the name `segment` than with `analytics`, but nevertheless there will still be people that run into this.

There is a reasonably low friction workaround proposed as well https://github.com/segmentio/analytics-python/issues/42#issuecomment-218803671. If there are issues with the workaround in https://github.com/segmentio/analytics-python/issues/42#issuecomment-218803671 let us know and we can reconsider.

Otherwise breaking backward compatibility just for a name change is not something we're prepared to do at the moment.
