### ISSUE TITLE
Docs - urls.py vs App Ready

### ISSUE THREAD

**Issue by shredding** [segmentio/analytics-python#59]
The docs state that I have to import analytics on the toplevel of django:

https://segment.com/docs/libraries/python/#django

First of all, this is outdated, as there is now an App Ready Hook Point in django: https://docs.djangoproject.com/en/dev/ref/applications/#django.apps.AppConfig.ready

Second: Can you elaborate why you are so fancy about having this in my urls.py?

I do not want to hardcode an external service at such a prominent point in my architecture and I do not understand the reasons why.

**Comment by calvinfo** [comment]
Totally. Good call on `ready` we can add that to our docs.

As for why it's called once, we spawn a new thread to make requests out of band so that it doesn't block your main program's execution, and so that we can take care of batching requests. We want to make sure that you're initializing once during the course of your program's run, so that we don't end up spawning a new thread on every request. The library itself ends up sort of like a database connection.
